[package]
name = "DiskScanner"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
chrono = "0.4"
iced = { version = "0.13.1", features = ["image", "lazy", "canvas"] } 
rfd = "0.15.0"
open = "5.3.0"